/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

import static intercode.Interviewee_working_area.b;
import static intercode.Interviewer_working_Area.textArea;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Serializable;
import java.io.*;
import static java.lang.Thread.sleep;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Highlighter;
import javax.swing.text.JTextComponent;
/**
 *
 * @author Bhanu Pratap Singh
 */
public class Interviewee_working_area extends javax.swing.JFrame {
 public static String path=null;
    static int milliseconds = 0;
    static int seconds = 0;
    static int minutes = 0;
    static int hours = 0;
    
    static boolean state = true;
    public static String ip ;
public static int count=1;   
static boolean b;
static int n,i,j;
//static ServerSocket ss1,ss2,ss3;
   static Socket s1,s2,s3,s4;
   static DataInputStream din1,din2,din3,din4;
   static DataOutputStream dout1,dout2,dout3,dout4;
    public static int port1,port2,port3,port4;
   static   String msgin1;
     static String msgin2="",msgin3="",msgin4="",t1,t2,t3,mail,pp;
    static String mail1;
  
static RSyntaxTextArea textArea = new RSyntaxTextArea(25, 80);

  static String email =Login_Signup.ssss2;

  



    public Interviewee_working_area() {
       fontdialog=new FontSelect1(this);
                
                /**
                 * This method is called from within the constructor to initialize the form.
                 * WARNING: Do NOT modify this code. The content of this method is always
                 * regenerated by the Form Editor.
                 */
                @SuppressWarnings("unchecked")
                // <editor-fold defaultstate="collapsed" desc="Generated Code">
                
         JPanel cp = new JPanel(new BorderLayout());

    
    
      textArea.setCodeFoldingEnabled(true);
      RTextScrollPane sp = new RTextScrollPane(textArea);
      cp.add(sp);

      setContentPane(cp);
      setTitle("Text Editor ");
      setDefaultCloseOperation(EXIT_ON_CLOSE);
      pack();
      setLocationRelativeTo(null);
        initComponents();
    
     
    }
       static void get(){
     try {
            dout2.writeUTF(textArea.getText());
        } catch (IOException ex) {
            Logger.getLogger(Interviewer_working_Area.class.getName()).log(Level.SEVERE, null, ex);
        } }
    
    private static final String JAVA_FILE_LOCATION1 =path+"\\Intercode\\BHANU.c";    
     private static final String JAVA_FILE_LOCATION2 =path+"\\Intercode\\BHANU.java";
      private static final String JAVA_FILE_LOCATION3 = path+"\\Intercode\\BHANU.cpp";
       private static final String JAVA_FILE_LOCATION4 = path+"\\Intercode\\BHANU.py";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ques = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        input = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lang = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        mess = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        sendtxt = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        hour = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        minute = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        millisecond = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Output");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 430, 300, 22);

        output.setEditable(false);
        output.setColumns(20);
        output.setRows(5);
        output.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                outputKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(output);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 460, 610, 200);

        ques.setEditable(false);
        ques.setColumns(20);
        ques.setRows(5);
        jScrollPane3.setViewportView(ques);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(650, 60, 450, 350);

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 430, 200, 30);

        jButton2.setText("Final Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(920, 430, 180, 30);

        input.setColumns(20);
        input.setRows(5);
        input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(input);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(650, 510, 450, 140);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Question");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(650, 30, 450, 30);

        lang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Language", "Java", "C", "C++", "Python" }));
        lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langActionPerformed(evt);
            }
        });
        jPanel1.add(lang);
        lang.setBounds(350, 430, 260, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(1200, 92, 30, 580);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Chat Area");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1230, 70, 300, 30);

        mess.setColumns(20);
        mess.setRows(5);
        jScrollPane5.setViewportView(mess);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(1220, 100, 320, 330);

        sendtxt.setColumns(20);
        sendtxt.setRows(5);
        jScrollPane6.setViewportView(sendtxt);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(1220, 480, 320, 130);

        jButton3.setText("Send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1350, 640, 61, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Type your message here");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1260, 450, 270, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Custom Input");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(670, 476, 420, 30);

        jButton4.setText("Clear Output Screen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(450, 660, 160, 25);

        jPanel2.setLayout(null);

        hour.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hour.setText("0");
        jPanel2.add(hour);
        hour.setBounds(10, 10, 50, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("hr.  :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 10, 60, 40);

        minute.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        minute.setText("0");
        jPanel2.add(minute);
        minute.setBounds(120, 10, 50, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("min. :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(170, 10, 70, 40);

        second.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        second.setText("0");
        jPanel2.add(second);
        second.setBounds(240, 10, 60, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("sec. :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(300, 10, 63, 40);

        millisecond.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        millisecond.setText("0");
        jPanel2.add(millisecond);
        millisecond.setBounds(370, 10, 70, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1100, 0, 460, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/int1561x725.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1560, 700);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 710));

        jMenu1.setText("File");

        jMenuItem5.setText("File path");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Find");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Replace");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("FindAll");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
System.out.println("frame area key event wrking...");
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String a = lang.getSelectedItem().toString();
     if(a.equalsIgnoreCase("C")){
                try {
          String filename = "BHANU.c";
        FileWriter fileWriter=new FileWriter(filename);
        fileWriter.write(textArea.getText());
        setTitle(filename);
        fileWriter.close();
        } catch (IOException e) {
                      System.out.println("file not found");          
        }
       String command[] = {"gcc",JAVA_FILE_LOCATION1};
       System.out.println("file compiled");
ProcessBuilder processBuilder = new ProcessBuilder(command);

Process process = null;
    try {
        process = processBuilder.start();
        OutputStream out = process.getOutputStream();
            out.write(input.getText().getBytes());
            out.close();
/**
         * Check if any errors or compilation errors encounter then print on Console.
         */
    } catch (IOException ex) {
        Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
    }


    try {
        if( process.getErrorStream().read() != -1 ){
            print("Compilation Errors",process.getErrorStream());
        }   } catch (IOException ex) {
        Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
    }
/**
* Check if javac process execute successfully or Not
* 0 - successful
*/
if( process.exitValue() == 0 ){
           try {
               process = new ProcessBuilder(new String[]{"a"}).start();
           } catch (IOException ex) {
               Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
               /** Check if RuntimeException or Errors encounter during execution then print errors on console
                * Otherwise print Output
                */
               if( process.getErrorStream().read() != -1 ){
                   print("Errors ",process.getErrorStream());
               }
               else{
                   print("Output ",process.getInputStream());
               }          } catch (IOException ex) {
               Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
           }

}
    }
    else if(a.equalsIgnoreCase("Java")){
            try {
          String filename = "BHANU.java";
        FileWriter fileWriter=new FileWriter(filename);
        fileWriter.write(textArea.getText());
        setTitle(filename);
        fileWriter.close();
        } catch (IOException e) {
                      System.out.println("file not found");          
        }
       String command[] = {"javac",JAVA_FILE_LOCATION2};
       System.out.println("file compiled");
ProcessBuilder processBuilder = new ProcessBuilder(command);

Process process = null;
    try {
        process = processBuilder.start();
        OutputStream out = process.getOutputStream();
            out.write(input.getText().getBytes());
            out.close();
/**
         * Check if any errors or compilation errors encounter then print on Console.
         */
    } catch (IOException ex) {
        Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
    }


    try {
        if( process.getErrorStream().read() != -1 ){
            print("Compilation Errors",process.getErrorStream());
        }   } catch (IOException ex) {
        Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
    }
/**
* Check if javac process execute successfully or Not
* 0 - successful
*/
if( process.exitValue() == 0 ){
           try {
               process = new ProcessBuilder(new String[]{"java","-cp","D:\\Desktop\\Intercode","Intercode"}).start();
           } catch (IOException ex) {
               Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
               /** Check if RuntimeException or Errors encounter during execution then print errors on console
                * Otherwise print Output
                */
               if( process.getErrorStream().read() != -1 ){
                   print("Errors ",process.getErrorStream());
               }
               else{
                   print("Output ",process.getInputStream());
               }          } catch (IOException ex) {
               Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
           }

}
    }
    else if(a.equalsIgnoreCase("C++")){
                try {
          String filename = "BHANU.cpp";
        FileWriter fileWriter=new FileWriter(filename);
        fileWriter.write(textArea.getText());
        setTitle(filename);
        fileWriter.close();
        } catch (IOException e) {
                      System.out.println("file not found");          
        }
       String command[] = {"g++",JAVA_FILE_LOCATION3};
       System.out.println("file compiled");
ProcessBuilder processBuilder = new ProcessBuilder(command);

Process process = null;
    try {
        process = processBuilder.start();
        OutputStream out = process.getOutputStream();
            out.write(input.getText().getBytes());
            out.close();
/**
         * Check if any errors or compilation errors encounter then print on Console.
         */
    } catch (IOException ex) {
        Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
    }


    try {
        if( process.getErrorStream().read() != -1 ){
            print("Compilation Errors",process.getErrorStream());
        }   } catch (IOException ex) {
        Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
    }
/**
* Check if javac process execute successfully or Not
* 0 - successful
*/
if( process.exitValue() == 0 ){
           try {
               process = new ProcessBuilder(new String[]{"a"}).start();
           } catch (IOException ex) {
               Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
               /** Check if RuntimeException or Errors encounter during execution then print errors on console
                * Otherwise print Output
                */
               if( process.getErrorStream().read() != -1 ){
                   print("Errors ",process.getErrorStream());
               }
               else{
                   print("Output ",process.getInputStream());
               }          } catch (IOException ex) {
               Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
           }

}
    }
    else if(a.equalsIgnoreCase("Python")){
         try {
          String filename = "BHANU.py";
        FileWriter fileWriter=new FileWriter(filename);
        fileWriter.write(textArea.getText());
        setTitle(filename);
        fileWriter.close();
        } catch (IOException e) {
                      System.out.println("file not found");          
        }
       String command[] = {"python",JAVA_FILE_LOCATION4};
       System.out.println("file compiled");
ProcessBuilder processBuilder = new ProcessBuilder(command);

Process process = null;
    try {
        process = processBuilder.start();
        OutputStream out = process.getOutputStream();
            out.write(input.getText().getBytes());
            out.close();
/**
         * Check if any errors or compilation errors encounter then print on Console.
         */
    } catch (IOException ex) {
        Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
    }


    try {
        if( process.getErrorStream().read() != -1 ){
            print("Compilation Errors",process.getErrorStream());
        }   } catch (IOException ex) {
        Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
    }
/**
* Check if javac process execute successfully or Not
* 0 - successful
*/
if( process.exitValue() == 0 ){
    //process = new ProcessBuilder(new String[]{"a"}).start();
    System.out.println("run successfully");
           try {
               /** Check if RuntimeException or Errors encounter during execution then print errors on console
                * Otherwise print Output
                */
               if( process.getErrorStream().read() != -1 ){
                   print("Errors ",process.getErrorStream());
               }
               else{
                   print("Output ",process.getInputStream());
               }          } catch (IOException ex) {
               Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
           }

}
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
output.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langActionPerformed
String s = lang.getSelectedItem().toString();
if(s.equalsIgnoreCase("C")){
     textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_C);
}
else if(s.equalsIgnoreCase("Java")){
     textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
}
else if(s.equalsIgnoreCase("C++")){
     textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_CPLUSPLUS);
}
else if(s.equalsIgnoreCase("Python")){
     textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_PYTHON);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_langActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        state=false;                                 //Timer stops
        textArea.setEditable(false);                 //editor area becomes non editable
        input.setEditable(false);                    //input area becomes non editable
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void outputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
        String msgout="";
       msgout=sendtxt.getText().trim();
       dout1.writeUTF(msgout);
       sendtxt.setText("");
      }catch(Exception e){} 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void inputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKeyReleased
          try {
            // TODO add your handling code here:for input area
            dout3.writeUTF(input.getText());
        } catch (IOException ex) {
            Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputKeyReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
 replace();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
find(0,true,false);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
String txt=JOptionPane.showInputDialog("Find");
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(null,"Enter valid string");
            return;
        }
        highlight(textArea,txt);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
callFontSelectDialog();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    class MyHighlightPainter extends DefaultHighlighter.DefaultHighlightPainter {
        public MyHighlightPainter(Color color) {
            super(color);
        }
    }
      Highlighter.HighlightPainter myHighlightPainter =  new MyHighlightPainter(Color.red);
      public void highlight(JTextComponent textComp,String pattern) {
        removeHighlight(textComp);
        try {
            Highlighter hilite = textComp.getHighlighter();
            Document doc = textComp.getDocument();
            String text=doc.getText(0,doc.getLength());
            int pos=0;
            while ((pos=text.toUpperCase().indexOf(pattern.toUpperCase(),pos))>=0) {
                hilite.addHighlight(pos,pos+pattern.length(),myHighlightPainter);
                pos+=pattern.length();
            } 
        } catch (Exception e) {
            
        }
    }
       public void removeHighlight(JTextComponent textComp) {
        Highlighter hilite = textComp.getHighlighter();
        Highlighter.Highlight[] hilites = hilite.getHighlights();
        for (int i=0;i<hilites.length;i++) {
            if (hilites[i].getPainter() instanceof MyHighlightPainter) {
                hilite.removeHighlight(hilites[i]);
            }
        }
    }
    private void find(int startIndex,boolean newWord,boolean caseSensitive) {
        if (newWord)
            findText=JOptionPane.showInputDialog("Find");
        if (findText!=null&&findText.equals("")) {
            JOptionPane.showMessageDialog(null,"Enter something to Find");
            return;
        }
        String find=findText;
        String data=textArea.getText();
        if (!caseSensitive) {
            find=find.toLowerCase();
            data=data.toLowerCase();
        }
        int len=data.length();
        start=startIndex;
        end=start;
        for (int i=start;i<len;i++) {
            char c=data.charAt(i);
            if (c==find.charAt(0)) {
                start=i;
                boolean flag=true;
                for (int j=0;j<find.length();j++,i++) {
                    if (i>=len||data.charAt(i)!=find.charAt(j)) {
                        flag=false;
                        break;
                    }
                }
                if (flag) {
                    end=i;
                    break;
                }
            }
        }
        if (start>=end) {
            if (startIndex!=0) {
                find(0,false,caseSensitive);
            }
            else {
                JOptionPane.showMessageDialog(null,findText+" Not Found");
                start=textArea.getCaretPosition();
                end=start;
            }
        }
        textArea.select(start, end);
    }
       public void replace()
       {
           findText=JOptionPane.showInputDialog("Find");
            replaceText=JOptionPane.showInputDialog("Replace");
             String d=textArea.getText();
             d=d.replaceAll(findText, replaceText);
             textArea.setText(d);
       }
        class FixedStack<T> extends Stack<T> {
    private final int maxSize;
    public FixedStack(int size) {
        super();
        this.maxSize=size;
    }
    @Override
    public T push(T object) {
        while (this.size()>=maxSize) {
            this.remove(0);
        }
        return super.push(object);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher(){
           @Override
           public boolean dispatchKeyEvent(KeyEvent e) {
              
               get();
               return false;
               
               
           }
            
            
            
        });
        Interviewee_working_area a = new Interviewee_working_area();
       
       
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(KeyEvent e) {
            
            return false;}
        });
            
            
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interviewee_working_area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interviewee_working_area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interviewee_working_area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interviewee_working_area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
        
       
        
        
        
         
         try{
           s2=new Socket(ip,2000);
             System.out.println("Rtextarea connected");
              din2 = new DataInputStream(s2.getInputStream());
           dout2=new DataOutputStream(s2.getOutputStream());
             
             Thread th6;
                    th6 = new Thread(new Runnable() {
                        @Override
                        public void run() {
                            
                            try {
                                while(true){
                                    System.out.println("waiting for rtaxt...");
                                    msgin2=din2.readUTF();
                                    textArea.setText(msgin2);
                                    System.out.println(" rsyantax recieved"+msgin2);}
                            } catch (IOException ex) { JOptionPane.showMessageDialog(null, "There may be a chance\n1.Interviewer is not ready\n2.Connection lost in between\n3.Interviewer is taking another interview");
                         
                            Interviewee_afterlogin t = new Interviewee_afterlogin();
                            t.setVisible(true);
                            Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
                            
                            
                            
                        }
                    });
             th6.start();
        
           
       }catch(Exception e){
       JOptionPane.showMessageDialog(null, "There may be a chance\n1.Interviewer is not ready\n2.Connection lost in between\n3.Interviewer is taking another interview");
       
       Interviewee_afterlogin t = new Interviewee_afterlogin();
       t.setVisible(true);
       }
         
         
            try{
     
       s1=new Socket(ip,3000);
           System.out.println("message connected");
       din1=new DataInputStream(s1.getInputStream());
       dout1=new DataOutputStream(s1.getOutputStream());
        Thread th7=new Thread(new Runnable() {
               @Override
               public void run() {
                   
                   try {  
                       while(true){
                  
                               msgin1 =din1.readUTF();
                              mess.setText(mess.getText().trim()+"\n"+msgin1);}
                   } catch (IOException ex) {
                       Logger.getLogger(Interviewee_working_area.class.getName()).log(Level.SEVERE, null, ex);
                   }
                          
               }
       });
             th7.start();
      
       }catch(Exception e){}
 try{            
    s3=new Socket(ip,4000);
          System.out.println("mail connected");
       din3=new DataInputStream(s3.getInputStream());
       dout3=new DataOutputStream(s3.getOutputStream());
       dout3.writeUTF(email);
       System.out.println("mail sent");
    
 }catch(IOException e){
     e.printStackTrace();
 }
           s4=new Socket(ip,5000);
          System.out.println("Questionarea connected");
       din4=new DataInputStream(s4.getInputStream());
       dout4=new DataOutputStream(s4.getOutputStream());
      Thread th5 = new Thread(new Runnable() {
        @Override
        public void run() {
            
              try{
      while(true)
       {
         msgin4=din4.readUTF();
         ques.setText(msgin4);
         t.start();
       }
       
      }catch(Exception ex){}  
        }
    });th5.start();
    
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interviewee_working_area().setVisible(true);
            }
        });
    }
   static  Thread t = new Thread()
        {
          public void run()
          {
              for(;;)
              {
                  if(state==true)
                  {
                      try
                      {
                          sleep(1);
                          
                          if(milliseconds>1000)
                          {
                              milliseconds=0;
                              seconds++;
                          }
                          if(seconds>60)
                          {
                              milliseconds=0;
                              seconds=0;
                              minutes++;
                          }
                          if(minutes>60)
                          {
                              milliseconds=0;
                              seconds=0;
                              minutes=0;
                              hours++;
                          }
                          
                          millisecond.setText(""+milliseconds);
                          milliseconds++;
                          second.setText(""+seconds);
                          minute.setText(""+minutes);
                          hour.setText(""+hours);
                          
                          
                      }
                      catch(Exception e)
                      {
                          
                      }
                  }
                  else
                  {
                      break;
                  }
              }
          }
        };
    
    int start,end;
public String findText;
public String replaceText;
 private Interviewer_working_Area.FixedStack<String> prev; 
    
   private void callFontSelectDialog() {
        fontdialog.setVisible(true);
    }  private final FontSelect1 fontdialog;


        
         public Color textColor;
public void setTextFont(Font font) {
        textArea.setFont(font);
        textArea.setForeground(textColor);
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel hour;
    private static javax.swing.JTextArea input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> lang;
    private static javax.swing.JTextArea mess;
    private static javax.swing.JLabel millisecond;
    private static javax.swing.JLabel minute;
    private javax.swing.JTextArea output;
    private static javax.swing.JTextArea ques;
    private static javax.swing.JLabel second;
    private javax.swing.JTextArea sendtxt;
    // End of variables declaration//GEN-END:variables

    private static String string;

    /**
     * Get the value of string
     *
     * @return the value of string
     */
    public static String getString() {
        return string;
    }

    /**
     * Set the value of string
     *
     * @param string new value of string
     */
    public static void setString(String string) {
        Interviewee_working_area.string = string;
    }
    
    private void print(String status,InputStream input) throws IOException{
BufferedReader in = new BufferedReader(new InputStreamReader(input));
System.out.println("************* "+status+"***********************");
//TF.setText("************* "+status+"***********************");
String line = "",k,g;
do{k=output.getText();

 System.out.println(line);

output.setText(k+"\n"+line);
}while((line = in.readLine()) != null );
in.close();
}

}
